services:
  energy-microservice:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: energy-microservice
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/energy_db
    volumes:
      - ./test_bia.csv:/app/test_bia.csv
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: energy_db
      TZ: America/Bogota
      PGTZ: America/Bogota
    command: ["postgres", "-c", "timezone=America/Bogota"]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d energy_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
